### ISSUE TITLE
Issue with ArrayType (serialize)

### ISSUE THREAD

**Issue by vulkodava** [doctrine/doctrine-website#244]
Hello,

I am using Doctrine ORM version ^2.5.6. It has some potential security issue. If you are able to as an array that would result in broken serialized string Doctrine does not check if the result string is a valid serialized array before storing it to the database. The next time you retrieve this value Doctrine throws a ConversionException that if not caught causes Denial of service.
Would it make sense to validate the string prior saving it to the database, say try unserializing it and throw the exception when trying to save such a string?

Thank you.

P.S. Same might be a valid issue for ObjectType as it also uses serialize, as I can see.

**Comment by vulkodava** [comment]
Moved to dbal project (https://github.com/doctrine/dbal/issues/3289)

**Comment by Ocramius** [comment]
Objects that are in memory and are to be handled by the ORM are under the direct responsibility of the developer using the ORM: the ORM limits itself to converting and saving whatever data it is given, no matter how malicious it may be. Having invalid data (according to type conversion) in the storage is also up to the user to fix, as the ORM works under the assumption of symmetricity between RDBMS and in-memory state, hence the (expected) type conversion exception.

I'll also add that you should contact maintainers in private if you suspect a security issue was found: making this stuff public would otherwise effectively be a 0-day disclosure.
