### ISSUE TITLE
Add support for defining version tags instead of branches

### ISSUE THREAD

**Issue by morozov** [doctrine/doctrine-website#369]
There's no much point in keeping the branches that correspond to the no longer supported versions in the repository. Contributors can create pull requests targeted at the branches that are no longer supported. The only reason we currently keep the branches in the DBAL is for the website.

This won't be necessary if the website can identify a no longer supported branch by its latest tag.

**Comment by SenseException** [comment]
This was mentioned internally in Slack and using tags instead of branches is going to be a new additional configuration in `.doctrine-project.json` files.

I considered to fix doctrine/dbal#3338 in the older branches first, because a waiting release of doctrine/rst-parser would break the build there. This would still need branches to be available in the repository, but I scrapped this idea. My current plan is to skip errors, if possible, for older unsupported versions.

After the default branch and build changes for the website are done, I can pick this one.

**Comment by morozov** [comment]
So far, I see that the `ProjectVersion` model already supports tags as such:
https://github.com/doctrine/doctrine-website/blob/2bec905fe15d5bed9231082749d0600ac52c519b/lib/Model/ProjectVersion.php#L69-L71
and the notion of the latest tag:
https://github.com/doctrine/doctrine-website/blob/2bec905fe15d5bed9231082749d0600ac52c519b/lib/Model/ProjectVersion.php#L168
Although I don't see any tests that would populate the tags from `.doctrine-project.json` nor I was able to find the projects that use tags in their project file. On the other hand, given that the website builder checks out the Git repo of the project anyways it could populate the model with the tags retrieved from Git.

**Comment by SenseException** [comment]
Tags are currently grouped with a version from the config file of a project (slug). If `branchName` becomes optional and the checkout process supports tags too, we could introduce tags for the documentation and don't need to have a branch for every old project version.
